# Generated by Django 5.1 on 2024-08-21 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='menu',
        ),
        migrations.AddField(
            model_name='blackcoffeemenuitem',
            name='name',
            field=models.CharField(default='Black Coffee', max_length=30),
        ),
        migrations.AddField(
            model_name='lattemenuitem',
            name='name',
            field=models.CharField(default='Latte', max_length=30),
        ),
        migrations.AddField(
            model_name='menu',
            name='black',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Menu.blackcoffeemenuitem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='latte',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Menu.lattemenuitem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='menuItems',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Menu.menuitem'),
            preserve_default=False,
        ),
    ]
