# Generated by Django 5.1 on 2024-08-21 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0003_alter_menu_menuitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menuItems',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Menu.menuitem'),
        ),
    ]
