# Generated by Django 5.1 on 2024-08-21 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Generic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='openinghours',
            options={'ordering': ('weekday', 'from_hour'), 'verbose_name_plural': 'Opening Hours'},
        ),
    ]
