# Generated by Django 5.1 on 2024-08-20 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoffeeShop', '0001_initial'),
        ('Generic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Generic.uslocation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='openingHours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Generic.openinghours'),
            preserve_default=False,
        ),
    ]
