# Generated by Django 5.1 on 2024-08-21 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoffeeShop', '0002_shop_address_shop_openinghours'),
        ('Generic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Generic.uslocation'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='openingHours',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Generic.openinghours'),
        ),
    ]
