# Generated by Django 5.1 on 2024-08-21 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoffeeShop', '0004_alter_shop_openinghours'),
        ('Menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='menu',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Menu.menu'),
        ),
    ]
