# Generated by Django 5.1 on 2024-08-21 18:15

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoffeeShop', '0005_alter_shop_menu'),
        ('Generic', '0002_alter_openinghours_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='openingHours',
        ),
        migrations.AlterField(
            model_name='shop',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='US'),
        ),
        migrations.AddField(
            model_name='shop',
            name='openingHours',
            field=models.ManyToManyField(to='Generic.openinghours'),
        ),
    ]
