# Generated by Django 5.1 on 2024-08-27 23:24
from django.contrib.postgres.operations import CreateExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoffeeShop', '0006_remove_shop_openinghours_alter_shop_phone_number_and_more'),
    ]

    operations = [
        CreateExtension("postgis"),
    ]
