# Generated by Django 5.1 on 2024-08-29 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoffeeShop', '0008_shop_point_alter_shop_lat_alter_shop_long'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/coffeeshop/', verbose_name='img'),
        ),
    ]
